#!/usr/bin/env python3
"""Exact finite B173 evaluation-code check; not a proof of HC."""

from fractions import Fraction
from itertools import product


def monomials(variables: int, degree: int) -> list[tuple[int, ...]]:
    return [
        exponents
        for exponents in product(range(degree + 1), repeat=variables)
        if sum(exponents) <= degree
    ]


def evaluate(point: tuple[int, ...], exponent: tuple[int, ...]) -> int:
    value = 1
    for coordinate, power in zip(point, exponent):
        value *= coordinate**power
    return value


def rank(matrix: list[list[Fraction]]) -> int:
    rows = [row[:] for row in matrix]
    if not rows:
        return 0
    pivot_row = 0
    for column in range(len(rows[0])):
        pivot = next(
            (i for i in range(pivot_row, len(rows)) if rows[i][column]),
            None,
        )
        if pivot is None:
            continue
        rows[pivot_row], rows[pivot] = rows[pivot], rows[pivot_row]
        scale = rows[pivot_row][column]
        rows[pivot_row] = [entry / scale for entry in rows[pivot_row]]
        for i, row in enumerate(rows):
            if i == pivot_row or not row[column]:
                continue
            factor = row[column]
            rows[i] = [
                entry - factor * pivot_entry
                for entry, pivot_entry in zip(row, rows[pivot_row])
            ]
        pivot_row += 1
        if pivot_row == len(rows):
            break
    return pivot_row


# Gradient of sum_i (z_i^4/4-z_i^3+z_i^2):
# P_i=z_i(z_i-1)(z_i-2). The 27 critical points form a reduced (3,3,3)
# complete intersection with s=5. For m=4, the maximal selector degree is 1.
gamma = list(product((0, 1, 2), repeat=3))
auxiliary = [point for point in gamma if point[0] == 0]
tracked = [point for point in gamma if point[0] != 0]
assert len(auxiliary) == 9
assert len(tracked) == 18

selector_monomials = monomials(3, 1)
auxiliary_evaluation = [
    [Fraction(evaluate(point, exponent)) for exponent in selector_monomials]
    for point in auxiliary
]
selector_kernel_dimension = len(selector_monomials) - rank(auxiliary_evaluation)
assert selector_kernel_dimension == 1  # generated by A=x

degree_four_monomials = monomials(3, 4)
tracked_evaluation = [
    [Fraction(evaluate(point, exponent)) for exponent in degree_four_monomials]
    for point in tracked
]
tracked_rank = rank(tracked_evaluation)
assert tracked_rank == 17
assert len(tracked) - tracked_rank == selector_kernel_dimension


def gradient_derivative(value: int) -> int:
    # derivative of z(z-1)(z-2)=z^3-3z^2+2z
    return 3 * value * value - 6 * value + 2


weighted_selector = []
for point in tracked:
    jacobian = 1
    for coordinate in point:
        jacobian *= gradient_derivative(coordinate)
    weighted_selector.append(Fraction(point[0], jacobian))

assert any(weighted_selector)
for column in range(len(degree_four_monomials)):
    pairing = sum(
        weighted_selector[row] * tracked_evaluation[row][column]
        for row in range(len(tracked))
    )
    assert pairing == 0

print("PASS: B173 selector dimension and Hessian-weighted dual kernel")
