"""Exact finite chain model for B112 and NG088."""

from fractions import Fraction


def boundary(chain):
    a, z = chain
    del z
    return a


reference = (Fraction(1), Fraction(0))
for coefficient in map(Fraction, (-3, -1, 0, 2, 5)):
    actual = (Fraction(1), coefficient)
    assert boundary(actual) == boundary(reference) == 1
    excess = (actual[0] - reference[0], actual[1] - reference[1])
    assert boundary(excess) == 0
    # H_k is generated by z; the excess coordinate is arbitrary.
    assert excess[1] == coefficient

print("PASS: B112 fixed marked boundary permits arbitrary excess class")
