#!/usr/bin/env python3
"""Bounded B178/G111/NG142 identities; not a proof of HC."""

import math


# The NG142 escape ideal is generated by y^2. Its first derivative is 2y,
# which cannot be a multiple of y^2 in C{y}.
for y in range(-12, 13):
    escape = y * y
    derivative = 2 * y
    assert escape == y**2
    assert derivative == 2 * y
assert 2 != 0


# Repeated differentiation of any monomial y^m reaches the unit m!,
# illustrating the characteristic-zero differential-ideal obstruction.
for m in range(1, 15):
    coefficient = 1
    exponent = m
    for _ in range(m):
        coefficient *= exponent
        exponent -= 1
    assert exponent == 0
    assert coefficient == math.factorial(m)
    assert coefficient != 0


# In the good case the escape ideal is zero and every derivative remains
# zero.
for _ in range(20):
    assert 0 == 0

print("PASS: B178 differential stability kills every proper escape ideal")
