#!/usr/bin/env python3
"""Exact B171/NG135 2x2 calculations; not a proof of HC."""


def det2(a, b, c, d):
    return a * d - b * c


# tau=(x,(1+y)x): Jacobian [[1,0],[1+y,x]].
for x in range(-12, 13):
    for y in range(-4, 5):
        determinant = det2(1, 0, 1 + y, x)
        assert determinant == x
        assert (determinant == 0) == (x == 0)

# Central relation (1,-1), mixed Hessian at (partial_x,partial_y).
d2_tau_1_xy = 0
d2_tau_2_xy = 1
mixed_relation_value = d2_tau_1_xy - d2_tau_2_xy
assert mixed_relation_value == -1

# Yet the ideal is generated by x and the lifted syzygy is exact.
for x in range(-9, 10):
    for y in range(-5, 6):
        tau1 = x
        tau2 = (1 + y) * x
        assert (1 + y) * tau1 - tau2 == 0

print("PASS: B171 mixed determinant obstruction separates G107 from H_tau=0")
