"""Exact rational checks for B134's two-branch dual relation coordinate."""

import sympy as sp


def relation_basis(delta: sp.Matrix) -> list[sp.Matrix]:
    return delta.nullspace()


def dual_cokernel_dimension(delta: sp.Matrix) -> int:
    # E = coker(Delta^*), canonically R^*.
    return delta.cols - delta.T.rank()


# One nonzero node: no relation and no dual target.
one = sp.Matrix([[1]])
assert len(relation_basis(one)) == 0
assert dual_cokernel_dimension(one) == 0

# Two independent nodes: again both spaces vanish.
independent = sp.eye(2)
assert len(relation_basis(independent)) == 0
assert dual_cokernel_dimension(independent) == 0

# If delta_2 = c delta_1, R is generated by c e_1-e_2 and E has dimension one.
c = sp.Rational(3, 2)
proportional = sp.Matrix([[1, c]])
relations = relation_basis(proportional)
assert len(relations) == 1
generator = sp.Matrix([c, -1])
assert proportional * generator == sp.zeros(1, 1)
assert sp.Matrix.hstack(relations[0], generator).rank() == 1
assert dual_cokernel_dimension(proportional) == 1

# Evaluation descends through coker(Delta^*): adding Delta^*(x) annihilates R.
u = sp.Matrix([sp.Rational(5, 3), sp.Rational(-7, 4)])
x = sp.Rational(11, 5)
shifted = u + proportional.T * x
assert (shifted.dot(generator) - u.dot(generator)) == 0

# The coordinate can still be zero although the relation space is nonzero.
zero_functional_representative = proportional.T
assert zero_functional_representative.dot(generator) == 0

print("PASS: B134 dual relation target and two-branch evaluation")
